FROM redis:alpine

# Create a custom config file
RUN mkdir -p /redis-data
RUN echo "maxmemory 28mb\n\
maxmemory-policy allkeys-lru\n\
appendonly yes\n\
save 60 1\n" > /redis-data/redis.conf

EXPOSE 6379

# Start Redis with our custom config
CMD ["redis-server", "/redis-data/redis.conf"]
